### ISSUE TITLE
Failed to resolve: com.linkedin.shaky:shaky:2.0.1

### ISSUE THREAD

**Issue by PabloMirandaGonzalez** [linkedin/shaky-android#29]
I'm trying to update to the last version, but gradle can't resolve the version 2.0.1.

**Comment by hongbinh** [comment]
Seems something wrong with our tool chain and the new version was not published successfully, we will look into the issue and keep you posted.

**Comment by jobernas** [comment]
Any update here?

**Comment by hongbinh** [comment]
We are still working on the issue, thanks for your patience and stay tuned.

**Comment by mockitoguy** [comment]
Hey guys, the library is published to JCenter: https://bintray.com/linkedin/maven/shaky, you should be able to get it from JCenter. Check Gradle docs how to add JCenter repo.

**Comment by drewhannay** [comment]
@mockitoguy The problem is that recent versions have been failing to publish to JCenter. Notice that the latest version there is `1.1.1`, but it should have `1.2.0`, `2.0.0`, and `2.0.1`

**Comment by iliao58** [comment]
Hey guys, the latest version for this library is now available.

**Comment by drewhannay** [comment]
Yes, all the versions are now available. We'll follow up separately to make sure future versions don't have the same issue.
